### ISSUE TITLE
add option 5) Ver inventario in main menu

### ISSUE THREAD

**Issue by Japoivvb** [AlexVolotka/AppTienda#1]
1. add new option in main menu, click on it or typing 5 a new window must appear with data loaded in inventory as show in below picture

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

![image](https://github.com/AlexVolotka/AppTienda/assets/36648472/e8057dd7-33ae-44fa-8e4d-89f00620fcda)

**Comment by AlexVolotka** [comment]
**Solved Check The Program**

**Comment by Japoivvb** [comment]
none commit with message linked to issue, no label, no evidence and you should not close it the issue, it is my task. Please add all tasks mentioned in issue description and reopen the issue

**Comment by AlexVolotka** [comment]
Solved There is the Prove
<img width="680" alt="Screenshot 2024-06-01 203832" src="https://github.com/AlexVolotka/AppTienda/assets/168207911/d898805e-1a8c-4fff-8318-2a06a679a34d">

**Comment by AlexVolotka** [comment]
Yo can check the numpad functionalities an the uptade by adding a new product

**Comment by Japoivvb** [comment]
1. ok
2. ko, 
3. ko,commit message does not include ref to issue 1
4. ok
5. ok
good job @AlexVolotka
